GENERATION_BOUNDARIES = [
    (1, 151),
    (2, 251),
    (3, 386),
    (4, 493),
    (5, 649),
    (6, 721),
    (7, 809),
    (8, 905),
    (9, 1025),
]

GENERATION_DEBUT_GAMES = {
    1: ["Red", "Blue"],
    2: ["Gold", "Silver"],
    3: ["Ruby", "Sapphire"],
    4: ["Diamond", "Pearl"],
    5: ["Black", "White"],
    6: ["X", "Y"],
    7: ["Sun", "Moon"],
    8: ["Sword", "Shield"],
    9: ["Scarlet", "Violet"],
}

POKEMON_TYPES = {
    "Normal": "#A8A77A",
    "Fire": "#EE8130",
    "Water": "#6390F0",
    "Electric": "#F7D02C",
    "Grass": "#7AC74C",
    "Ice": "#96D9D6",
    "Fighting": "#C22E28",
    "Poison": "#A33EA1",
    "Ground": "#E2BF65",
    "Flying": "#A98FF3",
    "Psychic": "#F95587",
    "Bug": "#A6B91A",
    "Rock": "#B6A136",
    "Ghost": "#735797",
    "Dragon": "#6F35FC",
    "Dark": "#705746",
    "Steel": "#B7B7CE",
    "Fairy": "#D685AD",
}

GAMES = [
    {"name": "Red", "generation": 1, "region": "Kanto"},
    {"name": "Blue", "generation": 1, "region": "Kanto"},
    {"name": "Yellow", "generation": 1, "region": "Kanto"},
    {"name": "Gold", "generation": 2, "region": "Johto"},
    {"name": "Silver", "generation": 2, "region": "Johto"},
    {"name": "Crystal", "generation": 2, "region": "Johto"},
    {"name": "Ruby", "generation": 3, "region": "Hoenn"},
    {"name": "Sapphire", "generation": 3, "region": "Hoenn"},
    {"name": "Emerald", "generation": 3, "region": "Hoenn"},
    {"name": "FireRed", "generation": 3, "region": "Kanto"},
    {"name": "LeafGreen", "generation": 3, "region": "Kanto"},
    {"name": "Diamond", "generation": 4, "region": "Sinnoh"},
    {"name": "Pearl", "generation": 4, "region": "Sinnoh"},
    {"name": "Platinum", "generation": 4, "region": "Sinnoh"},
    {"name": "HeartGold", "generation": 4, "region": "Johto"},
    {"name": "SoulSilver", "generation": 4, "region": "Johto"},
    {"name": "Black", "generation": 5, "region": "Unova"},
    {"name": "White", "generation": 5, "region": "Unova"},
    {"name": "Black 2", "generation": 5, "region": "Unova"},
    {"name": "White 2", "generation": 5, "region": "Unova"},
    {"name": "X", "generation": 6, "region": "Kalos"},
    {"name": "Y", "generation": 6, "region": "Kalos"},
    {"name": "Omega Ruby", "generation": 6, "region": "Hoenn"},
    {"name": "Alpha Sapphire", "generation": 6, "region": "Hoenn"},
    {"name": "Sun", "generation": 7, "region": "Alola"},
    {"name": "Moon", "generation": 7, "region": "Alola"},
    {"name": "Ultra Sun", "generation": 7, "region": "Alola"},
    {"name": "Ultra Moon", "generation": 7, "region": "Alola"},
    {"name": "Let's Go Pikachu", "generation": 7, "region": "Kanto"},
    {"name": "Let's Go Eevee", "generation": 7, "region": "Kanto"},
    {"name": "Sword", "generation": 8, "region": "Galar"},
    {"name": "Shield", "generation": 8, "region": "Galar"},
    {"name": "Brilliant Diamond", "generation": 8, "region": "Sinnoh"},
    {"name": "Shining Pearl", "generation": 8, "region": "Sinnoh"},
    {"name": "Legends: Arceus", "generation": 8, "region": "Hisui"},
    {"name": "Scarlet", "generation": 9, "region": "Paldea"},
    {"name": "Violet", "generation": 9, "region": "Paldea"},
    {"name": "Legends: Z-A", "generation": 9, "region": "Kalos"},
]

GAME_NAME_ALIASES = {
    "U.Sun": "Ultra Sun",
    "U.Moon": "Ultra Moon",
}

DLC_TO_PARENT_GAMES = {
    "The Isle of Armor": ["Sword", "Shield"],
    "The Crown Tundra": ["Sword", "Shield"],
    "The Teal Mask": ["Scarlet", "Violet"],
    "The Indigo Disk": ["Scarlet", "Violet"],
}