ALTER TABLE pokemon ENABLE ROW LEVEL SECURITY;
ALTER TABLE types ENABLE ROW LEVEL SECURITY;
ALTER TABLE pokemon_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE sprites ENABLE ROW LEVEL SECURITY;
ALTER TABLE games ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE regional_dex_numbers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read" ON pokemon FOR SELECT USING (true);
CREATE POLICY "public read" ON types FOR SELECT USING (true);
CREATE POLICY "public read" ON pokemon_types FOR SELECT USING (true);
CREATE POLICY "public read" ON sprites FOR SELECT USING (true);
CREATE POLICY "public read" ON games FOR SELECT USING (true);
CREATE POLICY "public read" ON locations FOR SELECT USING (true);
CREATE POLICY "public read" ON regional_dex_numbers FOR SELECT USING (true);
